# Generated by Django 3.1.5 on 2021-01-08 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='height',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(100, message='Value must be between 100 and 4000'), django.core.validators.MaxValueValidator(4000, message='Value must be between 100 and 4000')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='./sample_map.png', upload_to='upload/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='width',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(100, message='Value must be between 100 and 4000'), django.core.validators.MaxValueValidator(4000, message='Value must be between 100 and 4000')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
