# Generated by Django 3.1.5 on 2021-01-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210108_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blob',
            name='brain',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blob',
            name='color',
            field=models.CharField(default='rgb(0,0,0)', max_length=15),
        ),
        migrations.AddField(
            model_name='blob',
            name='energy',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='blob',
            name='memory',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='map',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
