# Generated by Django 3.1.5 on 2021-01-13 08:11

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210112_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='brain',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='map',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
